[package]
name = "const-rollup-config"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = "sovereign.xyz"
publish = false

[dependencies]
hex-literal = "0.3.4"